version: "3"

networks:
  mysql:
  base:

services:
  blog:
    image: nooox/blog
    restart: always
    ports:
      - "80:4000"
    networks:
      - base
    volumes:
      - "./themes:/root/lekkj"
      - "./themes:/root/blogs/themes"
      - "./config/_config.yml:/root/blogs/_config.yml"
      - "./config/_admin-config.yml:/root/blogs/_admin-config.yml"
      - "./source:/root/blogs/source"
